version: '3.8'

services:
  snake-game:
    image: nginx:alpine
    container_name: snake-game
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    restart: unless-stopped